// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaGBHqLeUvvEB85KWo9BmrYQ0RAg3cRXk',
    appId: '1:234163742578:web:107ba828ee353f2effdfeb',
    messagingSenderId: '234163742578',
    projectId: 'sino-mynotes',
    authDomain: 'sino-mynotes.firebaseapp.com',
    storageBucket: 'sino-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRD8OmV95EKUxA1RbUSZbd3B4WYdOAU8I',
    appId: '1:234163742578:android:7fd8ab30c1390859ffdfeb',
    messagingSenderId: '234163742578',
    projectId: 'sino-mynotes',
    storageBucket: 'sino-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlMjGNm57cMsUA30aI406ea_FON3cqOOo',
    appId: '1:234163742578:ios:384238e7113f7c84ffdfeb',
    messagingSenderId: '234163742578',
    projectId: 'sino-mynotes',
    storageBucket: 'sino-mynotes.appspot.com',
    iosBundleId: 'io.tcode.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlMjGNm57cMsUA30aI406ea_FON3cqOOo',
    appId: '1:234163742578:ios:384238e7113f7c84ffdfeb',
    messagingSenderId: '234163742578',
    projectId: 'sino-mynotes',
    storageBucket: 'sino-mynotes.appspot.com',
    iosBundleId: 'io.tcode.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaGBHqLeUvvEB85KWo9BmrYQ0RAg3cRXk',
    appId: '1:234163742578:web:aaa97fe10e8d6c1cffdfeb',
    messagingSenderId: '234163742578',
    projectId: 'sino-mynotes',
    authDomain: 'sino-mynotes.firebaseapp.com',
    storageBucket: 'sino-mynotes.appspot.com',
  );
}
